name: Deploy to dev-env
on: workflow_dispatch

jobs:
  deploy:
    # if: ${{ github.event.workfow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/env/dev

    steps:
      - name: Download the code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # - name: Build full image URL from tag
      #   run: |
      #     IMAGE_TAG=$(cat image_tag.txt)
      #     echo "IMAGE_TAG from artifact: $IMAGE_TAG"

      #     IMAGE_NAME=${ECR_REGISTRY}/${ECR_PUBLIC_ALIAS}/${ECR_REPOSITORY}:${IMAGE_TAG}
      #     echo "Full IMAGE_NAME: $IMAGE_NAME"

      #     # expose to later steps and to Terraform as TF_VAR_image
      #     echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
      #     echo "TF_VAR_image=$IMAGE_NAME" >> $GITHUB_ENV

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      - name: Build full image URL from tag
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_PUBLIC_ALIAS: ${{ secrets.ECR_PUBLIC_ALIAS }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          IMAGE_NAME=${ECR_REGISTRY}/${ECR_PUBLIC_ALIAS}/${ECR_REPOSITORY}:${IMAGE_TAG}
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "image=${IMAGE_NAME}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "image=${IMAGE_NAME}"




