name: Deploy to dev-env
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy (optional). If empty, the short GITHUB_SHA will be used.'
        required: false
        default: ''

jobs:
  deploy:
    # if: ${{ github.event.workfow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/env/dev

    steps:
      - name: Download the code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build full image URL from tag
        env:
          # input from workflow_dispatch; will be empty string if not provided
          INPUT_IMAGE_TAG: ${{ github.event.inputs.image_tag }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_PUBLIC_ALIAS: ${{ secrets.ECR_PUBLIC_ALIAS }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          ARTIFACTS_BUCKET: timo-artifact-bucket
          ARTIFACTS_PREFIX: dev
        run: |
          if [ -n "$INPUT_IMAGE_TAG" ]; then
            echo "Using image tag from input: $INPUT_IMAGE_TAG"
            IMAGE_TAG="$INPUT_IMAGE_TAG"
          else
            S3_KEY="${ARTIFACTS_PREFIX}/image_tag.txt"
            echo "No image_tag input provided, downloading from s3://${ARTIFACTS_BUCKET}/${S3_KEY}"
            aws s3 cp "s3://${ARTIFACTS_BUCKET}/${S3_KEY}" ./image_tag.txt
            IMAGE_TAG=$(cat image_tag.txt)
            echo "Using image tag from S3: $IMAGE_TAG"
          fi

          echo "IMAGE_TAG: $IMAGE_TAG"
          IMAGE_NAME=${ECR_REGISTRY}/${ECR_PUBLIC_ALIAS}/${ECR_REPOSITORY}:${IMAGE_TAG}
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "image=${IMAGE_NAME}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "image=${IMAGE_NAME}"
