name: Release and deploy to prod
on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag to deploy env from.'
        required: true
        default: ''

jobs:
  deploy:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/env/prod

    steps:
      - name: Download the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # number of commits to fetch (0 means ALL HISTORY)

      - name: Ensure release is ONLY made from main
        run: |
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            echo "::error::This workflow can only be run on the main branch."
            exit 1
          fi

      - name: Check git tag exists
        env:
          GIT_TAG: ${{ github.event.inputs.git_tag }}
        run: |
          echo "Checking if git tag ${GIT_TAG} exists..."
          if git show-ref --tags --verify --quiet "refs/tags/${GIT_TAG}";
          then
            echo "Git tag $GIT_TAG exists."
          else
            echo "Git tag $GIT_TAG does not exist. Exiting."
            exit 1
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create full image URL from tag
        env:
          GIT_TAG: ${{ github.event.inputs.git_tag }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_PUBLIC_ALIAS: ${{ secrets.ECR_PUBLIC_ALIAS }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
        run: |
          COMMIT_SHA=$(git rev-parse "${GIT_TAG}")
          IMAGE_NAME=${ECR_REGISTRY}/${ECR_PUBLIC_ALIAS}/${REPO_NAME}:${COMMIT_SHA}
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "image=${IMAGE_NAME}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "image=${IMAGE_NAME}"